---
title: "conditionals-loops"
author: "Melannie Moreno Rolon"
format: html
editor: visual
---

```{r}

library(tidyverse)
```

# Conditional statements & for loops

## Conditional statements

```{r}
# Task 1
pm2_5 <- 48

if (pm2_5 < 100){
  print("Low to moderate risk")
} else if (pm2_5 >= 100 & pm2_5 < 150) {
  print("Unhealthy for sensitive groups")
} else (pm2_5 >= 150) 
  print("Health risk present")
```

```{r}
#Task 2
species <- "blue whale"

if (str_detect(species, "whale")) {
  print("You found a whale!")
}
```

```{r}
#Task 3
base_burrito <- 6.50
main_ingredient <- "veggie"

# A veggie burrito is the cost of a base burrito
# A chicken burrito costs 3.00 more than a base burrito
# A steak burrito costs 3.25 more than a base burrito

#if-else if else statement
if(main_ingredient == "veggie") {
  print(base_burrito)
} else if (main_ingredient == "chicken") { 
  print(base_burrito + 3)
} else if (main_ingredient == "steak") {
  print(base_burrito + 3.25)}

#Switch statement
switch(main_ingredient,
       "veggie" = print(base_burrito),
       "chicken" = print(base_burrito + 3),
       "steak" = print(base_burrito + 3.25))
```

## For loops
```{r}
#Task 4

  #Creating a vector for the counts of different fish types in a fish tank 
  #(goldfish, tetras, guppies, and mollies, respectively)
fish_count <- c(8, 10, 12, 23)

  #Naming the previous vector (Assigning each vector value a name(string)"
names(fish_count) <- c("goldfish", "tetras", "guppies", "mollies")
fish_count

  #Sum of fish
fish_total = sum(fish_count)
fish_total

for (species in seq_along(fish_count)) {
  fish_prop = fish_count[species]/fish_total #Proportion calculation
  #Prints the fish type alongside the answer to the calculation
  print(paste(names(fish_count[species]), ":", round(fish_prop, 3)))
}



```

```{r}
#Task 5

for (i in seq_along(month.name)) { 
  print(paste(month.name[i], "is month", i)) #index the vector name gives the 
                                            #values inside, writing "i" alone
                                            #gives the index number  
}
```

